### ISSUE TITLE
Guides not sufficiently explaining how to use specific plugins

### ISSUE THREAD

**Issue by Adematics** [kestra-io/docs#1744]
### Description

Some of the how-to guides on the Kestra documentation page do not provide enough guidance on how to use the specific plugins they are meant to cover. Users may find it challenging to follow along due to the lack of detailed step-by-step instructions, example workflows, or plugin configuration options.

It would be helpful to enhance these guides by including:
- Detailed step-by-step instructions on use cases,
- Example workflows with context on when to use the plugin

Specifically, the following guides could benefit from such improvements: 
- [https://kestra.io/docs/how-to-guides/conditional-branching](https://kestra.io/docs/how-to-guides/conditional-branching)
- [https://kestra.io/docs/how-to-guides/loop](https://kestra.io/docs/how-to-guides/loop)
- [https://kestra.io/docs/how-to-guides/multiplecondition-listener](https://kestra.io/docs/how-to-guides/multiplecondition-listener)
```[tasklist]
### Tasks
- [x] https://kestra.io/docs/how-to-guides/conditional-branching
- [x] https://kestra.io/docs/how-to-guides/loop
- [x] https://kestra.io/docs/how-to-guides/multiplecondition-listener
```

**Comment by Ben8t** [comment]
Hello, thanks for opening this issue !

Do you have concrete examples you would like to see for these guides? I mean, there are already several [blueprints](https://kestra.io/blueprints) or [blog posts](https://kestra.io/blogs) covering most of the one you mentioned. 

(conditional branching -> [switch](https://kestra.io/blueprints?page=1&size=24&q=switch) and [if](https://kestra.io/blueprints?page=1&size=24&tags=If))
([loop or parallel blueprints](https://kestra.io/blueprints?page=1&size=24&tags=Parallel)
( [multiple condition](https://kestra.io/blueprints/trigger/80-trigger-a-flow-when-other-flows-finish-successfully)/[triggers](https://kestra.io/blueprints?page=1&size=24&tags=Trigger))

**Comment by Adematics** [comment]
Hello, thank you for your response!

While I appreciate the existing blueprints and blog posts, I noticed that some of the plugin-related guides lack in-depth, step-by-step examples that could help users implement these plugins effectively. I personally don't have a specific example use case, but I believe the how-to guides could use some improvements to better guide users in utilizing the plugins.

As it stands, the guides I listed seem more like sample blueprints rather than detailed guides. Providing more explanation on the plugins, common use cases, and example workflows (existing blueprints can be linked to the conclusion of the guide for the user to learn more) would make them more accessible for users who are new to Kestra or unfamiliar with these specific plugins.

**Comment by Ben8t** [comment]
Ok thanks for your clarification ! Are you open to contribute and open PR ?

**Comment by Adematics** [comment]
Yeah, I can find some time to work on it. You can assign the issue to me.

**Comment by Dev-Aditya-More** [comment]
Hello, If this issue is still active may i get assigned for the rest of the tasks?

**Comment by Adematics** [comment]
> Hello, If this issue is still active may i get assigned for the rest of the tasks?

you can work on the last one, am almost done with the second. @Dev-Aditya-More

**Comment by Dev-Aditya-More** [comment]
Hi, I've finished adding the tutorial for the Multiple Condition Listener. Should I go ahead and open a pull request for it?

**Comment by Ben8t** [comment]
@Dev-Aditya-More yes please do ! Thanks, we'll review :)

**Comment by Dev-Aditya-More** [comment]
yeah, pls review the pull request!

**Comment by Ben8t** [comment]
Can you link it here whenever you have something to share? Thanks :)

**Comment by Dev-Aditya-More** [comment]
Sure! Here’s the link: [(pull request)](https://github.com/kestra-io/docs/pull/1882)
Let me know if there's a change you want me to make. Thanks for reviewing!
